services:
  - type: web
    name: dr-mukil-studymate
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
